/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EspaceRouteImport } from './routes/espace'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthGmailCallbackRouteImport } from './routes/auth.gmail-callback'
import { Route as AuthenticatedWorkflowsRouteImport } from './routes/_authenticated.workflows'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated.templates'
import { Route as AuthenticatedTableauRouteImport } from './routes/_authenticated.tableau'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated.studio'
import { Route as AuthenticatedScriptsRouteImport } from './routes/_authenticated.scripts'
import { Route as AuthenticatedRevenusRouteImport } from './routes/_authenticated.revenus'
import { Route as AuthenticatedRelancesRouteImport } from './routes/_authenticated.relances'
import { Route as AuthenticatedRedactionRouteImport } from './routes/_authenticated.redaction'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated.profil'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated.pipeline'
import { Route as AuthenticatedPilotageRouteImport } from './routes/_authenticated.pilotage'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated.logs'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated.inbox'
import { Route as AuthenticatedFroidsRouteImport } from './routes/_authenticated.froids'
import { Route as AuthenticatedFacturationRouteImport } from './routes/_authenticated.facturation'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated.equipe'
import { Route as AuthenticatedConqueteRouteImport } from './routes/_authenticated.conquete'
import { Route as AuthenticatedChassePremiumRouteImport } from './routes/_authenticated.chasse-premium'
import { Route as AuthenticatedChasseRouteImport } from './routes/_authenticated.chasse'
import { Route as AuthenticatedApolloRouteImport } from './routes/_authenticated.apollo'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated.agenda'
import { Route as AuthenticatedProspectsIndexRouteImport } from './routes/_authenticated.prospects.index'
import { Route as AuthenticatedProspectsIdRouteImport } from './routes/_authenticated.prospects.$id'
import { Route as AuthenticatedFacturationReglagesRouteImport } from './routes/_authenticated.facturation.reglages'
import { Route as AuthenticatedFacturationPrestatairesRouteImport } from './routes/_authenticated.facturation.prestataires'
import { Route as AuthenticatedFacturationDeclarationsRouteImport } from './routes/_authenticated.facturation.declarations'
import { Route as AuthenticatedFacturationContratsRouteImport } from './routes/_authenticated.facturation.contrats'
import { Route as AuthenticatedStudioSiteIdRouteImport } from './routes/_authenticated.studio_.site.$id'
import { Route as AuthenticatedFacturationDocumentIdRouteImport } from './routes/_authenticated.facturation.document.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceRoute = EspaceRouteImport.update({
  id: '/espace',
  path: '/espace',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthGmailCallbackRoute = AuthGmailCallbackRouteImport.update({
  id: '/auth/gmail-callback',
  path: '/auth/gmail-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkflowsRoute = AuthenticatedWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTableauRoute = AuthenticatedTableauRouteImport.update({
  id: '/tableau',
  path: '/tableau',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScriptsRoute = AuthenticatedScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRevenusRoute = AuthenticatedRevenusRouteImport.update({
  id: '/revenus',
  path: '/revenus',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelancesRoute = AuthenticatedRelancesRouteImport.update({
  id: '/relances',
  path: '/relances',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRedactionRoute = AuthenticatedRedactionRouteImport.update({
  id: '/redaction',
  path: '/redaction',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPilotageRoute = AuthenticatedPilotageRouteImport.update({
  id: '/pilotage',
  path: '/pilotage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFroidsRoute = AuthenticatedFroidsRouteImport.update({
  id: '/froids',
  path: '/froids',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFacturationRoute =
  AuthenticatedFacturationRouteImport.update({
    id: '/facturation',
    path: '/facturation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConqueteRoute = AuthenticatedConqueteRouteImport.update({
  id: '/conquete',
  path: '/conquete',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChassePremiumRoute =
  AuthenticatedChassePremiumRouteImport.update({
    id: '/chasse-premium',
    path: '/chasse-premium',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChasseRoute = AuthenticatedChasseRouteImport.update({
  id: '/chasse',
  path: '/chasse',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApolloRoute = AuthenticatedApolloRouteImport.update({
  id: '/apollo',
  path: '/apollo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProspectsIndexRoute =
  AuthenticatedProspectsIndexRouteImport.update({
    id: '/prospects/',
    path: '/prospects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProspectsIdRoute =
  AuthenticatedProspectsIdRouteImport.update({
    id: '/prospects/$id',
    path: '/prospects/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFacturationReglagesRoute =
  AuthenticatedFacturationReglagesRouteImport.update({
    id: '/reglages',
    path: '/reglages',
    getParentRoute: () => AuthenticatedFacturationRoute,
  } as any)
const AuthenticatedFacturationPrestatairesRoute =
  AuthenticatedFacturationPrestatairesRouteImport.update({
    id: '/prestataires',
    path: '/prestataires',
    getParentRoute: () => AuthenticatedFacturationRoute,
  } as any)
const AuthenticatedFacturationDeclarationsRoute =
  AuthenticatedFacturationDeclarationsRouteImport.update({
    id: '/declarations',
    path: '/declarations',
    getParentRoute: () => AuthenticatedFacturationRoute,
  } as any)
const AuthenticatedFacturationContratsRoute =
  AuthenticatedFacturationContratsRouteImport.update({
    id: '/contrats',
    path: '/contrats',
    getParentRoute: () => AuthenticatedFacturationRoute,
  } as any)
const AuthenticatedStudioSiteIdRoute =
  AuthenticatedStudioSiteIdRouteImport.update({
    id: '/studio_/site/$id',
    path: '/studio/site/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFacturationDocumentIdRoute =
  AuthenticatedFacturationDocumentIdRouteImport.update({
    id: '/document/$id',
    path: '/document/$id',
    getParentRoute: () => AuthenticatedFacturationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/espace': typeof EspaceRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/apollo': typeof AuthenticatedApolloRoute
  '/chasse': typeof AuthenticatedChasseRoute
  '/chasse-premium': typeof AuthenticatedChassePremiumRoute
  '/conquete': typeof AuthenticatedConqueteRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/facturation': typeof AuthenticatedFacturationRouteWithChildren
  '/froids': typeof AuthenticatedFroidsRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/pilotage': typeof AuthenticatedPilotageRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/redaction': typeof AuthenticatedRedactionRoute
  '/relances': typeof AuthenticatedRelancesRoute
  '/revenus': typeof AuthenticatedRevenusRoute
  '/scripts': typeof AuthenticatedScriptsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/tableau': typeof AuthenticatedTableauRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/auth/gmail-callback': typeof AuthGmailCallbackRoute
  '/facturation/contrats': typeof AuthenticatedFacturationContratsRoute
  '/facturation/declarations': typeof AuthenticatedFacturationDeclarationsRoute
  '/facturation/prestataires': typeof AuthenticatedFacturationPrestatairesRoute
  '/facturation/reglages': typeof AuthenticatedFacturationReglagesRoute
  '/prospects/$id': typeof AuthenticatedProspectsIdRoute
  '/prospects/': typeof AuthenticatedProspectsIndexRoute
  '/facturation/document/$id': typeof AuthenticatedFacturationDocumentIdRoute
  '/studio/site/$id': typeof AuthenticatedStudioSiteIdRoute
}
export interface FileRoutesByTo {
  '/espace': typeof EspaceRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/apollo': typeof AuthenticatedApolloRoute
  '/chasse': typeof AuthenticatedChasseRoute
  '/chasse-premium': typeof AuthenticatedChassePremiumRoute
  '/conquete': typeof AuthenticatedConqueteRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/facturation': typeof AuthenticatedFacturationRouteWithChildren
  '/froids': typeof AuthenticatedFroidsRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/pilotage': typeof AuthenticatedPilotageRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/redaction': typeof AuthenticatedRedactionRoute
  '/relances': typeof AuthenticatedRelancesRoute
  '/revenus': typeof AuthenticatedRevenusRoute
  '/scripts': typeof AuthenticatedScriptsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/tableau': typeof AuthenticatedTableauRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/auth/gmail-callback': typeof AuthGmailCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/facturation/contrats': typeof AuthenticatedFacturationContratsRoute
  '/facturation/declarations': typeof AuthenticatedFacturationDeclarationsRoute
  '/facturation/prestataires': typeof AuthenticatedFacturationPrestatairesRoute
  '/facturation/reglages': typeof AuthenticatedFacturationReglagesRoute
  '/prospects/$id': typeof AuthenticatedProspectsIdRoute
  '/prospects': typeof AuthenticatedProspectsIndexRoute
  '/facturation/document/$id': typeof AuthenticatedFacturationDocumentIdRoute
  '/studio/site/$id': typeof AuthenticatedStudioSiteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/espace': typeof EspaceRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/apollo': typeof AuthenticatedApolloRoute
  '/_authenticated/chasse': typeof AuthenticatedChasseRoute
  '/_authenticated/chasse-premium': typeof AuthenticatedChassePremiumRoute
  '/_authenticated/conquete': typeof AuthenticatedConqueteRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/facturation': typeof AuthenticatedFacturationRouteWithChildren
  '/_authenticated/froids': typeof AuthenticatedFroidsRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/pilotage': typeof AuthenticatedPilotageRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/redaction': typeof AuthenticatedRedactionRoute
  '/_authenticated/relances': typeof AuthenticatedRelancesRoute
  '/_authenticated/revenus': typeof AuthenticatedRevenusRoute
  '/_authenticated/scripts': typeof AuthenticatedScriptsRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/tableau': typeof AuthenticatedTableauRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/workflows': typeof AuthenticatedWorkflowsRoute
  '/auth/gmail-callback': typeof AuthGmailCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/facturation/contrats': typeof AuthenticatedFacturationContratsRoute
  '/_authenticated/facturation/declarations': typeof AuthenticatedFacturationDeclarationsRoute
  '/_authenticated/facturation/prestataires': typeof AuthenticatedFacturationPrestatairesRoute
  '/_authenticated/facturation/reglages': typeof AuthenticatedFacturationReglagesRoute
  '/_authenticated/prospects/$id': typeof AuthenticatedProspectsIdRoute
  '/_authenticated/prospects/': typeof AuthenticatedProspectsIndexRoute
  '/_authenticated/facturation/document/$id': typeof AuthenticatedFacturationDocumentIdRoute
  '/_authenticated/studio_/site/$id': typeof AuthenticatedStudioSiteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/espace'
    | '/login'
    | '/signup'
    | '/agenda'
    | '/apollo'
    | '/chasse'
    | '/chasse-premium'
    | '/conquete'
    | '/equipe'
    | '/facturation'
    | '/froids'
    | '/inbox'
    | '/logs'
    | '/pilotage'
    | '/pipeline'
    | '/profil'
    | '/redaction'
    | '/relances'
    | '/revenus'
    | '/scripts'
    | '/studio'
    | '/tableau'
    | '/templates'
    | '/workflows'
    | '/auth/gmail-callback'
    | '/facturation/contrats'
    | '/facturation/declarations'
    | '/facturation/prestataires'
    | '/facturation/reglages'
    | '/prospects/$id'
    | '/prospects/'
    | '/facturation/document/$id'
    | '/studio/site/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/espace'
    | '/login'
    | '/signup'
    | '/agenda'
    | '/apollo'
    | '/chasse'
    | '/chasse-premium'
    | '/conquete'
    | '/equipe'
    | '/facturation'
    | '/froids'
    | '/inbox'
    | '/logs'
    | '/pilotage'
    | '/pipeline'
    | '/profil'
    | '/redaction'
    | '/relances'
    | '/revenus'
    | '/scripts'
    | '/studio'
    | '/tableau'
    | '/templates'
    | '/workflows'
    | '/auth/gmail-callback'
    | '/'
    | '/facturation/contrats'
    | '/facturation/declarations'
    | '/facturation/prestataires'
    | '/facturation/reglages'
    | '/prospects/$id'
    | '/prospects'
    | '/facturation/document/$id'
    | '/studio/site/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/espace'
    | '/login'
    | '/signup'
    | '/_authenticated/agenda'
    | '/_authenticated/apollo'
    | '/_authenticated/chasse'
    | '/_authenticated/chasse-premium'
    | '/_authenticated/conquete'
    | '/_authenticated/equipe'
    | '/_authenticated/facturation'
    | '/_authenticated/froids'
    | '/_authenticated/inbox'
    | '/_authenticated/logs'
    | '/_authenticated/pilotage'
    | '/_authenticated/pipeline'
    | '/_authenticated/profil'
    | '/_authenticated/redaction'
    | '/_authenticated/relances'
    | '/_authenticated/revenus'
    | '/_authenticated/scripts'
    | '/_authenticated/studio'
    | '/_authenticated/tableau'
    | '/_authenticated/templates'
    | '/_authenticated/workflows'
    | '/auth/gmail-callback'
    | '/_authenticated/'
    | '/_authenticated/facturation/contrats'
    | '/_authenticated/facturation/declarations'
    | '/_authenticated/facturation/prestataires'
    | '/_authenticated/facturation/reglages'
    | '/_authenticated/prospects/$id'
    | '/_authenticated/prospects/'
    | '/_authenticated/facturation/document/$id'
    | '/_authenticated/studio_/site/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  EspaceRoute: typeof EspaceRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthGmailCallbackRoute: typeof AuthGmailCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace': {
      id: '/espace'
      path: '/espace'
      fullPath: '/espace'
      preLoaderRoute: typeof EspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/gmail-callback': {
      id: '/auth/gmail-callback'
      path: '/auth/gmail-callback'
      fullPath: '/auth/gmail-callback'
      preLoaderRoute: typeof AuthGmailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workflows': {
      id: '/_authenticated/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthenticatedWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tableau': {
      id: '/_authenticated/tableau'
      path: '/tableau'
      fullPath: '/tableau'
      preLoaderRoute: typeof AuthenticatedTableauRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scripts': {
      id: '/_authenticated/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof AuthenticatedScriptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/revenus': {
      id: '/_authenticated/revenus'
      path: '/revenus'
      fullPath: '/revenus'
      preLoaderRoute: typeof AuthenticatedRevenusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relances': {
      id: '/_authenticated/relances'
      path: '/relances'
      fullPath: '/relances'
      preLoaderRoute: typeof AuthenticatedRelancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/redaction': {
      id: '/_authenticated/redaction'
      path: '/redaction'
      fullPath: '/redaction'
      preLoaderRoute: typeof AuthenticatedRedactionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pilotage': {
      id: '/_authenticated/pilotage'
      path: '/pilotage'
      fullPath: '/pilotage'
      preLoaderRoute: typeof AuthenticatedPilotageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/froids': {
      id: '/_authenticated/froids'
      path: '/froids'
      fullPath: '/froids'
      preLoaderRoute: typeof AuthenticatedFroidsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facturation': {
      id: '/_authenticated/facturation'
      path: '/facturation'
      fullPath: '/facturation'
      preLoaderRoute: typeof AuthenticatedFacturationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conquete': {
      id: '/_authenticated/conquete'
      path: '/conquete'
      fullPath: '/conquete'
      preLoaderRoute: typeof AuthenticatedConqueteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chasse-premium': {
      id: '/_authenticated/chasse-premium'
      path: '/chasse-premium'
      fullPath: '/chasse-premium'
      preLoaderRoute: typeof AuthenticatedChassePremiumRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chasse': {
      id: '/_authenticated/chasse'
      path: '/chasse'
      fullPath: '/chasse'
      preLoaderRoute: typeof AuthenticatedChasseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apollo': {
      id: '/_authenticated/apollo'
      path: '/apollo'
      fullPath: '/apollo'
      preLoaderRoute: typeof AuthenticatedApolloRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prospects/': {
      id: '/_authenticated/prospects/'
      path: '/prospects'
      fullPath: '/prospects/'
      preLoaderRoute: typeof AuthenticatedProspectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prospects/$id': {
      id: '/_authenticated/prospects/$id'
      path: '/prospects/$id'
      fullPath: '/prospects/$id'
      preLoaderRoute: typeof AuthenticatedProspectsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facturation/reglages': {
      id: '/_authenticated/facturation/reglages'
      path: '/reglages'
      fullPath: '/facturation/reglages'
      preLoaderRoute: typeof AuthenticatedFacturationReglagesRouteImport
      parentRoute: typeof AuthenticatedFacturationRoute
    }
    '/_authenticated/facturation/prestataires': {
      id: '/_authenticated/facturation/prestataires'
      path: '/prestataires'
      fullPath: '/facturation/prestataires'
      preLoaderRoute: typeof AuthenticatedFacturationPrestatairesRouteImport
      parentRoute: typeof AuthenticatedFacturationRoute
    }
    '/_authenticated/facturation/declarations': {
      id: '/_authenticated/facturation/declarations'
      path: '/declarations'
      fullPath: '/facturation/declarations'
      preLoaderRoute: typeof AuthenticatedFacturationDeclarationsRouteImport
      parentRoute: typeof AuthenticatedFacturationRoute
    }
    '/_authenticated/facturation/contrats': {
      id: '/_authenticated/facturation/contrats'
      path: '/contrats'
      fullPath: '/facturation/contrats'
      preLoaderRoute: typeof AuthenticatedFacturationContratsRouteImport
      parentRoute: typeof AuthenticatedFacturationRoute
    }
    '/_authenticated/studio_/site/$id': {
      id: '/_authenticated/studio_/site/$id'
      path: '/studio/site/$id'
      fullPath: '/studio/site/$id'
      preLoaderRoute: typeof AuthenticatedStudioSiteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facturation/document/$id': {
      id: '/_authenticated/facturation/document/$id'
      path: '/document/$id'
      fullPath: '/facturation/document/$id'
      preLoaderRoute: typeof AuthenticatedFacturationDocumentIdRouteImport
      parentRoute: typeof AuthenticatedFacturationRoute
    }
  }
}

interface AuthenticatedFacturationRouteChildren {
  AuthenticatedFacturationContratsRoute: typeof AuthenticatedFacturationContratsRoute
  AuthenticatedFacturationDeclarationsRoute: typeof AuthenticatedFacturationDeclarationsRoute
  AuthenticatedFacturationPrestatairesRoute: typeof AuthenticatedFacturationPrestatairesRoute
  AuthenticatedFacturationReglagesRoute: typeof AuthenticatedFacturationReglagesRoute
  AuthenticatedFacturationDocumentIdRoute: typeof AuthenticatedFacturationDocumentIdRoute
}

const AuthenticatedFacturationRouteChildren: AuthenticatedFacturationRouteChildren =
  {
    AuthenticatedFacturationContratsRoute:
      AuthenticatedFacturationContratsRoute,
    AuthenticatedFacturationDeclarationsRoute:
      AuthenticatedFacturationDeclarationsRoute,
    AuthenticatedFacturationPrestatairesRoute:
      AuthenticatedFacturationPrestatairesRoute,
    AuthenticatedFacturationReglagesRoute:
      AuthenticatedFacturationReglagesRoute,
    AuthenticatedFacturationDocumentIdRoute:
      AuthenticatedFacturationDocumentIdRoute,
  }

const AuthenticatedFacturationRouteWithChildren =
  AuthenticatedFacturationRoute._addFileChildren(
    AuthenticatedFacturationRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedApolloRoute: typeof AuthenticatedApolloRoute
  AuthenticatedChasseRoute: typeof AuthenticatedChasseRoute
  AuthenticatedChassePremiumRoute: typeof AuthenticatedChassePremiumRoute
  AuthenticatedConqueteRoute: typeof AuthenticatedConqueteRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFacturationRoute: typeof AuthenticatedFacturationRouteWithChildren
  AuthenticatedFroidsRoute: typeof AuthenticatedFroidsRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedPilotageRoute: typeof AuthenticatedPilotageRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedRedactionRoute: typeof AuthenticatedRedactionRoute
  AuthenticatedRelancesRoute: typeof AuthenticatedRelancesRoute
  AuthenticatedRevenusRoute: typeof AuthenticatedRevenusRoute
  AuthenticatedScriptsRoute: typeof AuthenticatedScriptsRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedTableauRoute: typeof AuthenticatedTableauRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedWorkflowsRoute: typeof AuthenticatedWorkflowsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProspectsIdRoute: typeof AuthenticatedProspectsIdRoute
  AuthenticatedProspectsIndexRoute: typeof AuthenticatedProspectsIndexRoute
  AuthenticatedStudioSiteIdRoute: typeof AuthenticatedStudioSiteIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedApolloRoute: AuthenticatedApolloRoute,
  AuthenticatedChasseRoute: AuthenticatedChasseRoute,
  AuthenticatedChassePremiumRoute: AuthenticatedChassePremiumRoute,
  AuthenticatedConqueteRoute: AuthenticatedConqueteRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFacturationRoute: AuthenticatedFacturationRouteWithChildren,
  AuthenticatedFroidsRoute: AuthenticatedFroidsRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedPilotageRoute: AuthenticatedPilotageRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedRedactionRoute: AuthenticatedRedactionRoute,
  AuthenticatedRelancesRoute: AuthenticatedRelancesRoute,
  AuthenticatedRevenusRoute: AuthenticatedRevenusRoute,
  AuthenticatedScriptsRoute: AuthenticatedScriptsRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedTableauRoute: AuthenticatedTableauRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedWorkflowsRoute: AuthenticatedWorkflowsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProspectsIdRoute: AuthenticatedProspectsIdRoute,
  AuthenticatedProspectsIndexRoute: AuthenticatedProspectsIndexRoute,
  AuthenticatedStudioSiteIdRoute: AuthenticatedStudioSiteIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  EspaceRoute: EspaceRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthGmailCallbackRoute: AuthGmailCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
