-- ─── Le Radar Tech — Découverte : Artefact Neural (projet de Nino Bondon) ──

insert into public.radar_articles (slug, title, kicker, category, standfirst, body, cover_url, author, status, featured, published_at) values
('artefact-neural-decouverte',
 'Découverte — Artefact Neural, la mémoire qui manque à votre IA',
 'Découverte', 'ia',
 'Porté par Nino Bondon, ce projet s’attaque à un défaut discret mais universel des assistants d’aujourd’hui : leur amnésie. Sa réponse tient en un mot — la mémoire, et elle reste entièrement sur votre machine.',
 '<p>Les intelligences artificielles nous éblouissent, puis nous exaspèrent. Brillantes une minute, elles oublient tout la suivante : à chaque nouvelle session, l’assistant repart de zéro, ignore votre code, vos décisions, vos habitudes. On réexplique, on recolle le contexte, on répète ce qu’on lui a appris la veille. C’est ce paradoxe — la puissance sans la mémoire — qu’attaque Artefact Neural, le projet de Nino Bondon.</p>
<figure style="margin:26px 0"><img src="https://images.unsplash.com/photo-1512314889357-e157c22f938d?auto=format&fit=crop&w=1200&q=70" alt="Notes et connaissance structurées" style="width:100%;border-radius:3px;display:block"><figcaption style="font-size:13px;color:#5c5852;margin-top:6px;font-family:Libre Franklin,sans-serif">Transformer sa connaissance — code, décisions, méthodes — en une mémoire que l’IA sait lire. — Unsplash</figcaption></figure>
<p>L’idée est limpide. Plutôt que de tout redemander, l’IA puise dans une mémoire structurée : votre savoir, vos choix, votre façon de faire, rangés et rendus consultables. Au cœur du dispositif, un moteur baptisé <em>Smart Brain</em> retrouve, en local, le bon passage — sourcé, vérifiable. Autour, plus de neuf cents notes prêtes à l’emploi et six agents chargés d’exécuter, vérifier, livrer. L’assistant cesse enfin de travailler dans le vide.</p>
<blockquote style="font-family:Spectral,serif;font-size:22px;line-height:1.4;font-style:italic;border-left:3px solid #9a2a2a;padding-left:18px;margin:28px 0;color:#2c2823">« Ton IA est brillante. Et amnésique. » Le slogan du projet résume, en cinq mots, un problème que des millions d’utilisateurs vivent sans savoir le nommer.</blockquote>
<p>Mais la vraie signature d’Artefact Neural est ailleurs, presque politique : tout se passe en local. Cent pour cent sur votre machine, zéro cloud, zéro télémétrie. Vos données ne sortent jamais. Là où l’industrie pousse chacun à déverser sa connaissance dans des serveurs lointains, ce projet fait le pari inverse — vous hébergez, vous exécutez, vous gardez le contrôle. Ce n’est pas un service géré que l’on loue, mais un système que l’on possède.</p>
<h2 class="serif" style="font-family:Spectral,serif;font-size:26px;margin:34px 0 12px">Un contre-pied assumé</h2>
<p>À rebours de la course aux modèles toujours plus gros et plus centralisés, Artefact Neural mise sur la sobriété et la souveraineté : une IA qui n’est pas plus puissante, mais qui vous connaît, sans jamais rien livrer à personne. Dans une Europe de plus en plus soucieuse de ses données, l’approche a de quoi séduire ceux — développeurs, indépendants, studios — que la dépendance au cloud inquiète.</p>
<blockquote style="font-family:Spectral,serif;font-size:22px;line-height:1.4;font-style:italic;border-left:3px solid #9a2a2a;padding-left:18px;margin:28px 0;color:#2c2823">Et si l’avenir n’était pas une IA qui sait tout, mais une IA qui se souvient de vous — chez vous ?</blockquote>
<p>Le projet ne prétend pas rivaliser avec les géants sur leur terrain. Il en défriche un autre : celui d’une intelligence artificielle personnelle, privée, ancrée dans le travail réel de son utilisateur. Un pari de niche, sans doute — mais aussi une intuition qui pourrait, demain, en inspirer beaucoup. Car la question que pose Artefact Neural dépasse l’outil : à l’ère de l’IA, qui doit détenir la mémoire de ce que nous savons ?</p>
<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">Découverte — la rédaction du Radar Tech. Source : artefactneural.com.</p>',
 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=1200&q=70',
 'La rédaction', 'publie', false, now() - interval '1 minute')
on conflict (slug) do nothing;
