-- ─── Le Radar Tech — allongement (lot A, 13 articles) ──────────────────
-- On insère des paragraphes supplémentaires AVANT le pied "Sources" (même
-- balise pour tous). Contenu original, factuel, sans redite ni citation inventée.

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>La prochaine étape porte déjà un nom : l’agent. Après l’assistant qui complète, voici le logiciel censé agir seul — ouvrir des fichiers, lancer des tests, corriger, recommencer. Les grands acteurs promettent qu’une part croissante des tâches d’ingénierie sera bientôt confiée à ces agents. La promesse est vertigineuse ; la réalité, plus prudente : sans supervision, un agent qui se trompe le fait à grande vitesse.</p><p>Cette bascule rebat les cartes du recrutement. Si écrire du code devient trivial, que reste-t-il au développeur junior pour faire ses gammes ? Les écoles et les entreprises cherchent la réponse. Une chose est sûre : la compétence rare n’est plus la syntaxe, mais la capacité à concevoir, à relire et à repérer l’erreur qu’une machine, elle, ne voit pas. C’est là que l’Europe, riche en talents mais pauvre en capitaux, garde une carte à jouer.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'assistants-code-ia';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>Au cœur du sujet, une réalité juridique méconnue : le droit américain peut contraindre une entreprise des États-Unis à livrer des données, où qu’elles soient hébergées dans le monde. Autrement dit, confier ses fichiers à un géant du cloud américain, même sur un serveur situé en Europe, n’offre pas les mêmes garanties que de les héberger chez un acteur soumis au seul droit européen. Cette asymétrie, longtemps théorique, est devenue un argument commercial.</p><p>Pour une organisation, la souveraineté se décline en gestes très concrets. La réversibilité, d’abord : pouvoir récupérer l’intégralité de ses données et repartir chez un autre, sans dépendre du bon vouloir de son fournisseur. Le chiffrement, ensuite, pour que même en cas d’accès forcé, les données restent illisibles. La localisation, enfin, mais aussi la nationalité juridique de l’hébergeur — car c’est elle, plus que l’adresse du serveur, qui décide qui peut, un jour, mettre la main sur vos informations.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'souverainete-donnees-europe';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>La cause du mal est d’abord économique. Pendant un siècle, la presse locale a vécu de la publicité de proximité — le garagiste, le notaire, le supermarché. Cette manne a migré, presque intégralement, vers deux géants américains qui vendent l’attention avec une précision que nul journal ne peut égaler. Privées de leur carburant, les rédactions ont taillé dans les effectifs, puis dans l’ambition, jusqu’à devenir parfois de simples coquilles.</p><p>Or l’enjeu dépasse le sort d’une profession. Là où l’information locale disparaît, des études constatent une baisse de la participation électorale, une hausse des coûts pour les collectivités et un terrain plus favorable à la corruption : sans journaliste pour assister au conseil municipal, personne ne surveille plus rien. Face à ce vide, des modèles neufs émergent — titres à but non lucratif, financement par les lecteurs, coopératives. La question n’est plus seulement de sauver des journaux, mais de préserver un bien commun : le regard que les citoyens portent sur leur propre territoire.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'presse-locale-algorithme';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>Pour comprendre ce que récompense Google, il faut connaître ses trois piliers, qu’il énonce lui-même : la pertinence (votre activité correspond-elle à la recherche ?), la distance (êtes-vous proche de l’internaute ?) et la notoriété (êtes-vous reconnu, cité, bien noté ?). Sur les deux premiers, on ne peut pas grand-chose. C’est sur le troisième que tout se joue.</p><p>Or beaucoup de commerçants négligent l’outil le plus puissant à leur portée, et pourtant gratuit : la fiche d’établissement. Une fiche complète, avec photos récentes, horaires exacts, catégories bien choisies et réponses aux avis, pèse souvent davantage qu’un site coûteux. À l’inverse, une incohérence — un numéro qui diffère d’un annuaire à l’autre, une adresse mal orthographiée — sème le doute chez l’algorithme comme chez le client. À l’ère des recherches « sans clic », où la réponse s’affiche directement sur la carte, cette vitrine est parfois le seul contact avant la visite. Autant la soigner.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'referencement-local-google';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>Le séisme ne touche pas tous les métiers de la même manière. L’illustration de commande, la photographie de stock, le doublage, la musique d’ambiance : partout où la production était déjà industrialisée, la machine s’installe vite. Ailleurs — la direction artistique, le récit, l’émotion singulière — l’humain conserve une longueur d’avance, et l’on voit même émerger une valeur nouvelle : la « prime à l’authenticité », ce supplément d’âme que le public paie précisément parce qu’il sait qu’une main l’a fait.</p><p>Reste la question qui empoisonne tout le débat : les données d’entraînement. Ces modèles ont appris en avalant des milliards d’images, de textes et de sons, souvent sans le consentement de leurs auteurs. Les procès se multiplient, les licences se négocient, et l’Europe légifère. De l’issue de cette bataille dépendra un équilibre fragile : celui entre la puissance de l’outil et le respect de ceux sans qui il n’existerait pas.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'ia-generative-metiers-creatifs';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>L’histoire regorge d’avertissements. Des créateurs qui avaient bâti des communautés de plusieurs millions d’abonnés ont vu, du jour au lendemain, un changement d’algorithme diviser leur portée par dix — ou une suspension de compte effacer des années de travail. Sur un terrain qu’on ne possède pas, la règle peut changer sans préavis, et sans recours.</p><p>Le théoricien Kevin Kelly a résumé la parade d’une formule devenue célèbre : mille vrais fans suffisent. Mille personnes qui vous suivent vraiment, dont vous détenez le contact direct, valent mieux qu’une audience massive mais empruntée. La stratégie qui en découle est limpide : utiliser les réseaux comme des affiches — pour attirer — mais toujours ramener vers un canal que l’on maîtrise, un site, une liste, où l’on capte une adresse. La visibilité se loue ; la relation, elle, se possède.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'reseaux-sociaux-audience';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>Un mot d’explication, car le sujet paraît technique : le nom de domaine est enregistré auprès d’un « bureau d’enregistrement », le registrar. C’est lui qui facture le renouvellement, souvent annuel, et c’est dans son interface que se règlent les paramètres invisibles — les fameux « DNS » qui relient votre nom à votre site et à vos emails. Perdre l’accès à ce compte, c’est perdre la clé de tout l’édifice.</p><p>Les histoires qui finissent mal se ressemblent : une facture de renouvellement partie dans les indésirables, un prestataire qui cesse son activité, un ancien associé resté seul titulaire. À chaque fois, le site s’éteint et les emails cessent, parfois en pleine activité. Trois précautions suffisent pourtant à dormir tranquille : être soi-même le titulaire officiel, activer le renouvellement automatique avec une carte à jour, et protéger le compte du registrar par une double authentification. Rien de sorcier — seulement de la rigueur, là où l’enjeu est vital.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'heberger-donnees-europe-guide';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>Ce retournement met fin à une décennie que les développeurs eux-mêmes appelaient la « fatigue JavaScript » : ce vertige d’un écosystème où un outil chassait l’autre avant même qu’on ait fini de l’apprendre. À force de complexité, beaucoup de sites étaient devenus des cathédrales fragiles, lentes à charger et coûteuses à entretenir.</p><p>Le balancier revient vers le bon sens. Le rendu côté serveur, un temps délaissé, retrouve ses lettres de noblesse ; des approches minimalistes prônent d’en faire moins, mais mieux. Pour le client final, la traduction est très concrète : un site sobre coûte moins cher à faire évoluer, se charge plus vite — ce que Google et les visiteurs récompensent — et survit aux modes. La performance et la durabilité, longtemps sacrifiées sur l’autel de la nouveauté, redeviennent enfin des critères de choix.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'javascript-frameworks-2026';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>Concrètement, cette immersion prend souvent la forme d’une journée sur le terrain — dans l’atelier, la boutique ou le cabinet. On observe les gestes, on écoute les clients, on note les objections récurrentes. De ce matériau brut naît une hiérarchie : quel est le message qui doit frapper en premier, quelle preuve rassure immédiatement, quel bouton l’on veut voir cliqué. Rien n’est laissé au hasard esthétique tant que cette colonne vertébrale n’est pas posée.</p><p>Vient ensuite ce que l’on mesure trop rarement : la vie du site après la mise en ligne. Les pages les plus visitées, les endroits où l’on décroche, les demandes qui aboutissent. Ces chiffres, relus chaque mois, disent où ajuster un titre, remplacer une photo, clarifier un parcours. Un site n’est pas une œuvre que l’on inaugure ; c’est un outil que l’on affûte — et c’est ce suivi discret qui, mois après mois, transforme une jolie vitrine en machine à faire venir des clients.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'wyngo-fabrique-site';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>Le no-code a pourtant ses limites, qu’il faut connaître avant de s’enfermer. La première est la dépendance : bâtir tout son outil sur une plateforme, c’est en accepter les tarifs, les règles et les éventuelles fermetures. La seconde est le plafond : passé une certaine complexité ou un certain volume, ces solutions montrent leurs coutures, et il faut alors envisager du sur-mesure. Le bon réflexe consiste à démarrer vite en no-code pour valider une idée, tout en gardant la maîtrise de ses données et de son nom de domaine, afin de pouvoir migrer sans repartir de zéro.</p><p>Ce mouvement porte un nom : le « citizen developer », ce non-informaticien qui construit lui-même ses outils. Il démocratise la création logicielle comme le tableur l’a fait pour le calcul. Mais il ne dispense pas de méthode : un bel outil au service d’un projet flou ne produit rien. La technique n’a jamais remplacé la clarté de l’intention.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'cinq-outils-no-code';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>Que recouvrent, au juste, ces exigences ? Des choses souvent invisibles pour qui voit clair : un contraste suffisant entre le texte et le fond, une image toujours accompagnée d’une description pour ceux qui ne la voient pas, une navigation possible au seul clavier, des formulaires clairement étiquetés. Rien d’exotique : les bonnes pratiques que tout site soigné applique déjà.</p><p>Attention, en revanche, aux fausses solutions. Des éditeurs vendent des « widgets » censés rendre un site accessible d’un clic ; les associations de personnes handicapées les dénoncent comme des cache-misère, parfois pires que le mal. L’accessibilité ne se rajoute pas par-dessus : elle se pense dès la conception. Et le jeu en vaut la chandelle, car ce qui sert une personne malvoyante sert aussi le référencement, la lecture sur mobile et le confort de tous. La contrainte réglementaire, ici, ne fait qu’imposer ce que le bon sens recommandait déjà.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'accessibilite-numerique-obligation';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>Le scénario d’une attaque est presque toujours le même. Tout commence par un courriel piégé : un employé clique, une porte s’ouvre. L’intrus progresse alors discrètement dans le réseau, repère les sauvegardes, les copie — puis chiffre tout et réclame une rançon. La tendance récente, dite de « double extorsion », ajoute la menace de publier les données volées : payer ne suffit plus à effacer le préjudice.</p><p>Face à cela, la meilleure défense reste étonnamment accessible. Des sauvegardes régulières et déconnectées permettent de tout restaurer sans payer. La double authentification bloque l’essentiel des intrusions. Les mises à jour ferment les failles connues. La sensibilisation des équipes, enfin, désamorce l’hameçonnage à la source. L’assurance cyber peut compléter le dispositif, mais elle ne remplace pas l’hygiène : aucune police ne rend le temps perdu ni la confiance des clients. Pour une petite structure, la cybersécurité n’est pas une forteresse coûteuse — c’est une routine.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'rancongiciels-tpe-cible';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>Rappelons ce dont il est question. Un cookie « tiers » est un petit fichier déposé par un autre site que celui qu’on visite, qui permet de suivre l’internaute de page en page pour lui servir des publicités ciblées. C’est le carburant de la publicité en ligne moderne — et la bête noire des défenseurs de la vie privée.</p><p>Puisqu’ils demeurent, faut-il en conclure que rien ne change ? Pas tout à fait. La décennie de débats a durablement déplacé les lignes : la publicité se réoriente vers la donnée dite « de première partie » — celle que chaque site collecte lui-même, avec consentement — et vers le ciblage par le contexte plutôt que par l’espionnage du parcours. Pour une petite entreprise, la morale est intacte : la donnée la plus précieuse, la plus stable et la plus éthique reste celle qu’on recueille en direct auprès de ses propres clients. Elle ne dépend ni d’un navigateur, ni d’un géant, ni d’un revirement.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'cookies-tiers-renoncement-google';
