-- ─── Le référentiel métiers, complet ─────────────────────────────────
--
-- La première version dédupliquait par code NAF : 287 métiers du catalogue
-- tombaient à 188. Kinésithérapeute et Psychologue libéral partagent 86.90F,
-- ils étaient donc fondus en un seul — alors que ce sont deux missions
-- différentes, avec deux discours différents.
--
-- On garde les 287, identifiés par leur id de catalogue.
--
-- Ce que ça n'efface pas : la recherche d'entreprises ne filtre que sur le
-- code NAF (un seul métier du catalogue porte des mots-clés). Les 9 métiers
-- en 86.90F ramènent donc les mêmes cabinets. C'est pourquoi la contrainte
-- d'unicité des secteurs reste sur (naf, commune) : deux personnes ne peuvent
-- pas recevoir deux libellés différents qui aboutiraient au même appel.

drop table if exists public.metiers_prospection;

create table public.metiers_prospection (
  metier_id text primary key,
  naf       text not null,
  label     text not null,
  actif     boolean not null default true
);

create index metiers_naf_idx on public.metiers_prospection (naf);

alter table public.metiers_prospection enable row level security;
create policy "metiers_lecture" on public.metiers_prospection
  for select to authenticated using (true);

insert into public.metiers_prospection (metier_id, naf, label) values
('boulangerie','10.71B','Boulangerie - Pâtisserie'),
('patisserie','10.71C','Pâtisserie artisanale'),
('chocolaterie','10.82Z','Chocolaterie - Confiserie'),
('glacier','10.52Z','Glacier - Fabricant de glaces'),
('torrefacteur','10.83Z','Torréfacteur - Café artisanal'),
('boucherie','47.22Z','Boucherie - Charcuterie'),
('poissonnerie','47.23Z','Poissonnerie'),
('fromagerie','47.29Z','Fromagerie - Crémerie'),
('caviste','47.25Z','Caviste - Vins & spiritueux'),
('epicerie','47.29Z','Épicerie fine'),
('epicerie_bio','47.21Z','Magasin bio / vrac'),
('traiteur','56.21Z','Traiteur événementiel'),
('primeur','47.21Z','Primeur / Fruits & légumes'),
('brasserie_artisanale','11.05Z','Brasserie artisanale (bière)'),
('distillerie','11.01Z','Distillerie artisanale'),
('conserverie','10.39B','Conserverie artisanale'),
('huilerie','10.41B','Huilerie artisanale'),
('tabac_presse','47.26Z','Tabac - Presse - Loto'),
('restaurant','56.10A','Restaurant traditionnel'),
('restaurant_gastro','56.10A','Restaurant gastronomique'),
('fastfood','56.10C','Restauration rapide'),
('pizzeria','56.10B','Pizzeria'),
('creperie','56.10C','Crêperie'),
('food_truck','56.10C','Food truck - Cuisine mobile'),
('sandwicherie','56.10C','Sandwicherie - Snacking'),
('bar_cafe','56.30Z','Bar - Café - Brasserie'),
('salon_the','56.30Z','Salon de thé - Coffee shop'),
('bar_vin','56.30Z','Bar à vin'),
('bar_cocktails','56.30Z','Bar à cocktails - Speakeasy'),
('pub','56.30Z','Pub - Brasserie irlandaise'),
('club_discotheque','56.30Z','Discothèque - Club'),
('kebab_oriental','56.10C','Kebab - Cuisine orientale'),
('sushi','56.10A','Restaurant japonais - Sushi'),
('coiffure','96.02A','Salon de coiffure'),
('barbier','96.02A','Barbier - Barbershop'),
('esthetique','96.02B','Institut de beauté'),
('onglerie','96.02B','Onglerie - Prothésiste ongulaire'),
('spa','96.04Z','Spa - Centre bien-être'),
('hammam','96.04Z','Hammam - Sauna'),
('massage','96.04Z','Centre de massages'),
('bronzage','96.04Z','Centre de bronzage - UV'),
('epilation_laser','96.02B','Centre d''épilation laser'),
('maquilleur','96.02B','Maquilleur professionnel'),
('maquillage_permanent','96.02B','Maquillage permanent / Dermographie'),
('tatoueur','96.09Z','Tatoueur - Perceur'),
('fleuriste','47.76Z','Fleuriste'),
('librairie','47.61Z','Librairie - Papeterie'),
('bijouterie','47.77Z','Bijouterie - Horlogerie'),
('opticien','47.78A','Opticien'),
('pharmacie','47.73Z','Pharmacie'),
('decoration','47.59B','Décoration - Ameublement'),
('meubles','47.59A','Magasin de meubles'),
('cuisiniste','47.59A','Cuisiniste - Vente de cuisines'),
('salle_bain_equipement','47.52B','Salle de bain - Équipement'),
('poeles_cheminees','47.52B','Poêles & cheminées'),
('luminaires','47.59B','Magasin de luminaires'),
('jouets','47.65Z','Jeux & jouets'),
('sport_articles','47.64Z','Articles de sport'),
('magasin_cycles','47.64Z','Magasin de cycles - Vélos'),
('magasin_peche','47.64Z','Magasin de pêche'),
('magasin_chasse','47.78C','Armurerie - Magasin de chasse'),
('parfumerie','47.75Z','Parfumerie - Cosmétiques'),
('informatique','47.41Z','Informatique - Réparation'),
('telephonie','47.42Z','Téléphonie - Multimédia'),
('electromenager','47.54Z','Électroménager'),
('musique_instruments','47.59A','Instruments de musique'),
('antiquaire','47.79Z','Antiquaire - Brocante'),
('friperie','47.79Z','Friperie - Dépôt-vente'),
('concession_auto','45.11Z','Concession automobile'),
('magasin_velo_elec','47.64Z','Magasin de vélos électriques'),
('vetements','47.71Z','Magasin de vêtements'),
('chaussures','47.72A','Magasin de chaussures'),
('maroquinerie','47.72B','Maroquinerie'),
('lingerie','47.71Z','Lingerie - Sous-vêtements'),
('styliste','14.13Z','Créateur de mode - Styliste'),
('atelier_couture','14.13Z','Atelier de couture sur mesure'),
('tissus','47.51Z','Magasin de tissus - Mercerie'),
('plombier','43.22A','Plombier - Chauffagiste'),
('electricien','43.21A','Électricien bâtiment'),
('climatisation','43.22B','Climatisation - Pompe à chaleur'),
('menuisier','43.32A','Menuisier bois'),
('menuisier_alu','43.32B','Menuisier alu / PVC'),
('carreleur','43.33Z','Carreleur - Revêtements'),
('peintre','43.34Z','Peintre - Décorateur'),
('vitrier','43.34Z','Vitrier - Miroitier'),
('platrier','43.31Z','Plâtrier - Plaquiste'),
('couvreur','43.91A','Couvreur - Charpentier'),
('zinguerie','43.91B','Zinguerie - Étanchéité toit'),
('macon','43.99C','Maçon - Gros œuvre'),
('isolation','43.29A','Isolation - ITE / ITI'),
('facade_ravalement','43.99B','Façadier - Ravalement'),
('paysagiste','81.30Z','Paysagiste - Jardinier'),
('elagueur','81.30Z','Élagueur - Cordiste'),
('serrurier','25.71Z','Serrurier - Métallerie'),
('storiste','43.34Z','Storiste - Stores - Volets'),
('constructeur_maisons','41.20A','Constructeur de maisons'),
('piscines','43.99B','Constructeur de piscines'),
('amenagement_combles','43.32A','Aménagement combles - Extension'),
('terrassement','43.12B','Terrassement - VRD'),
('demolition','43.11Z','Démolition'),
('desinsectisation','81.29Z','Désinsectisation - Nuisibles'),
('ramoneur','81.22Z','Ramoneur - Fumisterie'),
('energies_renouvelables','43.22B','Énergies renouvelables - Solaire'),
('horloger','95.25Z','Horloger - Réparation'),
('luthier','32.20Z','Luthier - Réparation d''instruments'),
('ebeniste','31.09A','Ébéniste'),
('tapissier','13.92Z','Tapissier d''ameublement'),
('ferronnier_art','25.99B','Ferronnier d''art'),
('vitrailliste','23.19Z','Vitrailliste - Maître verrier'),
('ceramiste_potier','23.41Z','Céramiste - Potier'),
('marbrier','23.70Z','Marbrier - Sculpteur sur pierre'),
('forgeron','25.50A','Forgeron - Coutelier'),
('bijoutier_createur','32.12Z','Bijoutier-créateur'),
('restaurateur_oeuvres','90.03B','Restaurateur d''œuvres d''art'),
('relieur','18.14Z','Relieur - Doreur'),
('encadreur','47.78B','Encadreur d''art'),
('garage','45.20A','Garage automobile'),
('carrosserie','45.20B','Carrosserie - Peinture auto'),
('pneus','45.20A','Centre pneumatiques'),
('lavage_auto','45.20A','Lavage auto - Detailing'),
('moto_garage','45.40Z','Vente / Réparation moto'),
('depannage_remorquage','52.21Z','Dépannage - Remorquage'),
('voitures_occasion','45.11Z','Vente voitures d''occasion'),
('location_voitures','77.11A','Location de voitures'),
('vitrage_auto','45.20A','Vitrage auto - Pare-brise'),
('controle_technique','71.20A','Contrôle technique'),
('medecin','86.21Z','Médecin généraliste'),
('pediatre','86.22A','Pédiatre'),
('dentiste','86.23Z','Cabinet dentaire'),
('orthodontiste','86.23Z','Orthodontiste'),
('kine','86.90F','Kinésithérapeute'),
('osteo','86.90E','Ostéopathe'),
('podologue','86.90C','Podologue - Pédicure'),
('veterinaire','75.00Z','Vétérinaire'),
('infirmiere','86.90D','Infirmier(ère) libéral(e)'),
('sage_femme','86.90D','Sage-femme libérale'),
('audioprothesiste','47.74Z','Audioprothésiste'),
('dieteticien','86.90F','Diététicien - Nutritionniste'),
('psychologue','86.90F','Psychologue libéral'),
('psychomotricien','86.90F','Psychomotricien'),
('ergotherapeute','86.90F','Ergothérapeute'),
('orthophoniste','86.90F','Orthophoniste'),
('sophrologue','86.90F','Sophrologue'),
('naturopathe','86.90F','Naturopathe'),
('hypnotherapeute','86.90F','Hypnothérapeute'),
('salle_sport','93.13Z','Salle de sport - Fitness'),
('crossfit','93.13Z','Box CrossFit'),
('yoga_pilates','85.51Z','Studio yoga / Pilates'),
('coach_sportif','85.51Z','Coach sportif personnel'),
('boxe_arts_martiaux','93.13Z','Boxe - Arts martiaux'),
('escalade_salle','93.13Z','Salle d''escalade'),
('tennis_club','93.12Z','Club de tennis'),
('golf_club','93.12Z','Club / Practice de golf'),
('equitation','93.19Z','Centre équestre - Manège'),
('danse','85.52Z','École de danse'),
('musique_ecole','85.52Z','École de musique'),
('ecole_natation','85.51Z','École de natation'),
('ecole_ski','85.51Z','École de ski - Moniteur'),
('auto_ecole','85.53Z','Auto-école'),
('bowling','93.29Z','Bowling'),
('laser_game','93.29Z','Laser game - Quasar'),
('escape_game','93.29Z','Escape game'),
('karting','93.29Z','Karting'),
('paintball','93.29Z','Paintball - Airsoft'),
('cinema_local','59.14Z','Cinéma indépendant'),
('theatre_salle','90.04Z','Théâtre - Salle de spectacle'),
('hotel','55.10Z','Hôtel'),
('hotel_charme','55.10Z','Hôtel de charme - Boutique-hôtel'),
('chambres_hotes','55.20Z','Chambres d''hôtes'),
('gite','55.20Z','Gîte rural'),
('camping','55.30Z','Camping - Glamping'),
('meubles_tourisme','55.20Z','Location meublés tourisme'),
('agence_voyage','79.11Z','Agence de voyage'),
('tour_operator','79.12Z','Tour-opérateur'),
('guide_touristique','79.90Z','Guide touristique - Excursion'),
('pressing','96.01A','Pressing - Blanchisserie'),
('cordonnerie','95.23Z','Cordonnerie - Clés - Imprimerie minute'),
('couturière','95.29Z','Retouches - Couturière'),
('photographe','74.20Z','Photographe (portrait, mariage)'),
('pompes_funebres','96.03Z','Pompes funèbres'),
('aide_domicile','88.10A','Aide à domicile - Auxiliaire de vie'),
('garde_enfants','88.91A','Garde d''enfants - Crèche privée'),
('soutien_scolaire','85.60Z','Soutien scolaire - Cours particuliers'),
('coach_vie','85.59B','Coach de vie - Life coach'),
('mediateur_familial','88.99B','Médiateur familial'),
('voyance','96.09Z','Voyance - Astrologie'),
('wedding_planner','74.90B','Wedding planner'),
('evenementiel_particulier','82.30Z','Organisation événements particuliers'),
('demenageur','49.42Z','Déménageur'),
('garde_meubles','52.10B','Garde-meubles - Stockage'),
('comptable','69.20Z','Expertise comptable'),
('avocat','69.10Z','Cabinet d''avocats'),
('notaire','69.10Z','Étude notariale'),
('huissier','69.10Z','Huissier de justice'),
('commissaire_comptes','69.20Z','Commissaire aux comptes'),
('conseil','70.22Z','Conseil aux entreprises'),
('coach_business','70.22Z','Coach business / professionnel'),
('consultant_strategie','70.22Z','Consultant stratégie'),
('architecte','71.11Z','Architecte DPLG'),
('architecte_interieur','71.11Z','Architecte d''intérieur'),
('decorateur','74.10Z','Décorateur d''intérieur - Home stager'),
('ingenierie','71.12B','Bureau d''études - Ingénierie'),
('diagnostic_thermique','71.20B','Diagnostic thermique - DPE'),
('geometre','71.12A','Géomètre-expert'),
('agence_com','73.11Z','Agence de communication'),
('graphiste','74.10Z','Graphiste - Designer'),
('traducteur','74.30Z','Traducteur - Interprète'),
('imprimerie','18.12Z','Imprimerie - Reprographie'),
('videaste_pro','59.11C','Vidéaste - Films d''entreprise'),
('drone_pilote','74.90B','Pilote de drone professionnel'),
('menage_pro','81.21Z','Nettoyage professionnel'),
('securite_privee','80.10Z','Sécurité privée - Gardiennage'),
('telesurveillance','80.20Z','Télésurveillance - Alarme'),
('rh_recrutement','78.10Z','Cabinet RH - Recrutement'),
('interim','78.20Z','Agence d''intérim'),
('formation_pro','85.59A','Organisme de formation professionnelle'),
('courtier_assurance','66.22Z','Courtier en assurance'),
('courtier_credit','66.19A','Courtier en crédit / Mortgage'),
('conseil_patrimoine','66.22Z','Conseiller en gestion de patrimoine'),
('logistique','52.29B','Logistique - Transport'),
('developpeur_web','62.01Z','Développeur web - Agence digitale'),
('agence_seo','73.11Z','Agence SEO / SEA'),
('community_manager','73.11Z','Community manager freelance'),
('redacteur_web','90.03B','Rédacteur web - Copywriter'),
('ux_ui_designer','74.10Z','UX / UI designer'),
('motion_designer','59.12Z','Motion designer - Animation 2D/3D'),
('hebergeur_sysadmin','63.11Z','Hébergement web - Infogérance'),
('cybersecurite','62.02A','Consultant cybersécurité'),
('dpo_rgpd','62.02A','DPO - Conseil RGPD'),
('studio_jeux_video','58.21Z','Studio de jeux vidéo'),
('modeleur_3d','74.10Z','Modeleur 3D - Animation 3D'),
('influenceur_createur','73.11Z','Créateur de contenu / Influenceur'),
('immobilier_agence','68.31Z','Agence immobilière'),
('mandataire_immo','68.31Z','Mandataire immobilier'),
('gestion_immo','68.32A','Administration de biens'),
('diagnostiqueur','71.20B','Diagnostiqueur immobilier'),
('promoteur','41.10A','Promoteur immobilier'),
('marchand_biens','68.10Z','Marchand de biens'),
('lotisseur','41.10B','Lotisseur - Aménageur foncier'),
('home_staging','74.10Z','Home staging - Mise en valeur'),
('photographe_immobilier','74.20Z','Photographe immobilier'),
('maraicher','01.13Z','Maraîcher - AMAP'),
('viticulteur','01.21Z','Viticulteur - Vigneron'),
('apiculteur','01.49Z','Apiculteur - Miel artisanal'),
('producteur_fromager','10.51A','Producteur fromager fermier'),
('eleveur','01.41Z','Éleveur - Vente directe'),
('pepinieriste','01.30Z','Pépiniériste - Plantes'),
('horticulteur','01.19Z','Horticulteur'),
('animalerie','47.76Z','Animalerie'),
('toiletteur','96.09Z','Toiletteur canin / félin'),
('pension_animaux','96.09Z','Pension pour animaux'),
('educateur_canin','96.09Z','Éducateur canin - Dresseur'),
('comportementaliste_animal','96.09Z','Comportementaliste animal'),
('pet_sitter','96.09Z','Pet-sitter - Visites à domicile'),
('clinique-privee','86.10Z','Clinique privée'),
('maison-sante','86.21Z','Maison de santé pluridisciplinaire'),
('centre-dentaire','86.23Z','Centre dentaire'),
('centre-imagerie','86.22A','Centre d''imagerie médicale - Radiologie'),
('laboratoire-analyses','86.90B','Laboratoire d''analyses médicales'),
('centre-reeducation','86.90E','Centre de rééducation - Soins de suite'),
('ehpad','87.10A','EHPAD - Maison de retraite médicalisée'),
('residence-senior','87.30A','Résidence senior'),
('negoce-materiaux','46.73A','Négoce de matériaux de construction'),
('grossiste-quincaillerie','46.74A','Grossiste quincaillerie - Outillage pro'),
('fournitures-industrielles','46.69C','Fournitures et équipements industriels'),
('grossiste-alimentaire','46.39B','Grossiste alimentaire'),
('grossiste-entretien','46.44Z','Grossiste produits d''entretien - Hygiène'),
('grossiste-boissons','46.34Z','Grossiste boissons - Vins et spiritueux'),
('equipement-chr','46.69B','Matériel de restauration professionnel - CHR'),
('distributeur-pieces-auto','45.31Z','Distributeur de pièces automobiles'),
('distributeur-medical','46.46Z','Distributeur de matériel médical'),
('mobilier-bureau-pro','46.65Z','Mobilier et fournitures de bureau'),
('usinage-precision','25.62B','Usinage - Mécanique de précision'),
('tolerie-chaudronnerie','25.11Z','Tôlerie - Chaudronnerie'),
('traitement-surface','25.61Z','Traitement et revêtement de surface'),
('plasturgie','22.29A','Plasturgie - Pièces techniques plastique'),
('agroalimentaire-transfo','10.89Z','Transformation agroalimentaire'),
('fabricant-mobilier','31.09B','Fabricant de mobilier'),
('menuiserie-industrielle','16.23Z','Menuiserie industrielle - Charpente'),
('maintenance-industrielle','33.12Z','Maintenance industrielle'),
('syndic-copropriete','68.32A','Syndic de copropriété'),
('intermediaire-financier','66.19B','Intermédiaire en services financiers'),
('gestion-portefeuille','66.30Z','Société de gestion de portefeuille'),
('agent-assurance','66.22Z','Agent général d''assurance'),
('expert-assurance','66.21Z','Expert en assurance - Évaluation des risques'),
('recouvrement-creances','82.91Z','Société de recouvrement de créances'),
('domiciliation-entreprises','82.11Z','Cabinet de domiciliation d''entreprises')
on conflict (metier_id) do nothing;
