-- ─── Le Radar Tech — allongement (lot B, 12 articles) ──────────────────

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>Ce renouveau a aussi son économie. Là où le web gratuit vivait de publicité, la newsletter a réhabilité un modèle plus ancien : l’abonnement. Des plumes indépendantes vivent aujourd’hui de quelques milliers de lecteurs payants — un artisanat éditorial impensable il y a dix ans. Le lien direct devient un revenu direct.</p><p>Mais le canal exige une discipline que les réseaux ne réclamaient pas. Une adresse mail est un territoire intime : on n’y entre pas pour rien. La régularité, la qualité, la délivrabilité — cet art discret d’éviter le dossier « indésirables » — font la différence entre une lettre attendue et un abonné perdu. C’est le retour, sous une forme moderne, d’une figure que l’on croyait dépassée : le rédacteur en chef, garant d’une promesse tenue numéro après numéro.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'email-newsletter-reprend-pouvoir';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>Derrière ce réflexe, un ressort psychologique vieux comme le commerce : la preuve sociale. Nous faisons confiance à ce que d’autres ont validé avant nous ; l’étoile a simplement remplacé le bouche-à-oreille du marché. Ce pouvoir attire les tricheurs, et les autorités s’en emparent : en Europe comme aux États-Unis, la répression des faux avis se durcit, avec des sanctions à la clé pour ceux qui achètent leur réputation.</p><p>Pour un commerçant honnête, la meilleure stratégie n’a rien de sophistiqué. Solliciter un avis au bon moment — juste après un service réussi —, remercier les clients satisfaits, et surtout répondre avec calme aux mécontents : une critique bien traitée en public rassure souvent plus qu’une note parfaite. Car le client ne cherche pas la perfection, il cherche des preuves d’humanité. Reste une vigilance : ne jamais dépendre d’une seule plateforme, dont un changement de règle peut, du jour au lendemain, rebattre les cartes de votre réputation.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'avis-en-ligne-economie-reputation';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>Pour saisir le vertige, il faut comprendre comment se construit un logiciel moderne. Aucun n’est écrit d’un bloc : chacun empile des dizaines, parfois des milliers de briques libres, elles-mêmes dépendantes d’autres briques. Cet empilement, invisible, forme une chaîne dont la solidité tient à son maillon le plus faible — souvent un projet tenu à bout de bras par une seule personne.</p><p>Des réponses s’organisent. En Allemagne, un fonds public — le Sovereign Tech Fund — finance directement l’entretien des logiciels critiques ; l’idée essaime en Europe. Les entreprises, de leur côté, adoptent la notion de « nomenclature logicielle », l’inventaire précis des composants d’un produit, afin de savoir enfin de quoi elles dépendent. Car on ne protège que ce que l’on connaît. Savoir de quelles briques son site est fait, entretenues par qui, n’est plus une curiosité d’ingénieur : c’est une question de sécurité collective.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'open-source-securite-financement';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>L’ironie de cette réussite tient à ses origines. OpenAI naît fin 2015 comme un laboratoire à but non lucratif, cofondé notamment par Elon Musk, avec une mission presque messianique : faire en sorte que l’intelligence artificielle « bénéficie à toute l’humanité ». De GPT-1 aux modèles suivants, l’entreprise a d’abord été un centre de recherche discret — jusqu’au lancement de ChatGPT, fin 2022, qui a fait basculer le monde en quelques semaines.</p><p>Pour financer cette ambition, il a fallu composer avec le capital. Un partenariat massif avec Microsoft, une structure hybride mêlant intérêt général et profit, une gouvernance mise à l’épreuve : la maison vit une tension permanente entre sa mission affichée et la réalité d’une industrie qui engloutit des milliards en puces et en électricité. Cette contradiction fondatrice — sauver l’humanité tout en levant les plus grosses sommes de l’histoire — reste la clé pour comprendre OpenAI. Et la principale interrogation qui pèse sur son avenir.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'openai-startup-plus-chere-monde';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>La singularité d’Anthropic tient à sa méthode autant qu’à son discours. L’entreprise a popularisé une approche baptisée « IA constitutionnelle » : plutôt que de corriger le modèle au cas par cas, on lui donne un ensemble de principes — une sorte de constitution — à partir desquels il apprend à s’autoréguler. En parallèle, ses chercheurs travaillent à ouvrir la « boîte noire » des réseaux de neurones, pour comprendre ce qui se passe réellement à l’intérieur. Un chantier aussi fondamental qu’inachevé.</p><p>Ce positionnement lui a valu des alliés de poids : Amazon et Google comptent parmi ses principaux soutiens, chacun voyant dans la maison un contrepoids à OpenAI. Reste le paradoxe qui hante Anthropic : prêcher la prudence tout en participant à une course effrénée. Ses fondateurs l’assument comme un moindre mal — mieux vaut, disent-ils, que les plus soucieux de sécurité soient aussi parmi les plus avancés. L’argument convainc les entreprises, plus soucieuses de fiabilité que de records.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'anthropic-prudence-comme-arme';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>Le pedigree des fondateurs explique en partie la crédibilité immédiate de Mistral. Arthur Mensch vient de Google DeepMind ; Guillaume Lample et Timothée Lacroix ont fait leurs armes dans le laboratoire d’IA de Meta. Trois anciens des géants qu’ils défient aujourd’hui, forts d’une conviction : l’ouverture. Là où les Américains verrouillent leurs modèles, Mistral en publie une partie, laissant chacun les inspecter et les faire tourner — un pari sur la confiance et la communauté.</p><p>Cette philosophie rencontre un contexte favorable. L’Europe s’est dotée d’un cadre réglementaire, l’AI Act, qui impose transparence et responsabilité — un terrain où l’ouverture devient un atout plutôt qu’une contrainte. Mistral y ajoute son propre assistant, Le Chat, et une obsession : combler le retard d’infrastructure du continent. Le défi reste immense, tant l’écart de moyens est abyssal. Mais l’entreprise a déjà prouvé le principal : qu’une voix européenne pouvait, enfin, se faire entendre dans un débat confisqué par deux nations.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'mistral-ai-pari-francais';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>Il faut distinguer deux moments dans la vie d’un modèle. L’entraînement, d’abord : une phase colossale, longue de plusieurs mois, où le système ingère des montagnes de données pour ajuster des milliards de paramètres — un investissement en puces et en énergie qui se chiffre en centaines de millions. L’utilisation, ensuite : chaque fois que vous posez une question, le modèle « infère », c’est-à-dire calcule sa réponse à partir de ce qu’il a appris, sans jamais réapprendre.</p><p>Une loi empirique gouverne le domaine : plus on augmente la taille du modèle, la quantité de données et la puissance de calcul, meilleurs sont les résultats. C’est cette « loi d’échelle » qui a déclenché la course aux géants. Pour affiner le comportement, on ajoute une couche d’apprentissage guidé par des humains, qui notent les réponses pour orienter le modèle vers ce qui est utile et acceptable. Mais rien de tout cela ne crée une compréhension : la machine reste un imitateur d’une virtuosité stupéfiante, dont la première qualité — prédire le plausible — est aussi le premier défaut. D’où ces « hallucinations » énoncées avec l’aplomb de la vérité.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'comment-fonctionne-vraiment-ia';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>Pourquoi maintenant ? Trois forces se conjuguent. La course à l’IA, d’abord, qui pousse les géants à s’emparer des talents et des briques stratégiques avant leurs rivaux. Des trésoreries pléthoriques, ensuite : les grandes plateformes croulent sous le cash et cherchent où l’investir. Une forme d’urgence, enfin — dans une industrie où six mois font une éternité, il est souvent plus rapide d’acheter que de construire.</p><p>Cette frénésie inquiète les régulateurs, en Europe comme aux États-Unis, qui redoutent une concentration excessive. Elle transforme aussi la stratégie des start-up : beaucoup ne visent plus l’indépendance, mais le rachat, quitte à voir leur produit absorbé, transformé ou éteint. Pour les utilisateurs — entreprises comme particuliers — la leçon est ancienne et toujours d’actualité : ne jamais confier tout son destin à un outil qu’un géant peut, du jour au lendemain, racheter et faire disparaître.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'rachats-tech-annee-records';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>Framework s’inscrit dans un mouvement plus vaste, né de la colère : celui du droit à la réparation. Des collectifs comme iFixit publient depuis des années des guides pour démonter et réparer soi-même, contre une industrie qui a longtemps tout fait pour l’en empêcher — pièces indisponibles, colle à la place des vis, logiciels bridés. La marque a transformé ce combat militant en produit désirable.</p><p>Son pari repose sur un écosystème : une place de marché de modules et de pièces détachées qui prolonge la vie de l’appareil et fédère une communauté de bricoleurs. Les obstacles demeurent — produire à petite échelle coûte cher, et le durable se paie parfois d’un léger surcoût à l’achat. Mais le vent réglementaire souffle dans le bon sens : la France a instauré un indice de réparabilité, et l’Europe généralise l’idée. Ce que Framework faisait par conviction devient, peu à peu, la norme que tous devront suivre.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'framework-ordinateur-reparable';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>Le mode d’emploi de Bending Spoons tient en quelques principes, appliqués avec une froideur assumée. Racheter un produit qui a déjà trouvé son public, mais mal géré. Réduire les coûts — souvent par des vagues de licenciements —, augmenter les tarifs, rationaliser la technique, puis conserver l’actif sur le long terme pour en tirer une rente. Là où les fonds classiques revendent, l’italien garde et presse.</p><p>Ce modèle divise profondément. Ses défenseurs y voient une discipline salutaire, qui sauve des logiciels autrement condamnés ; ses détracteurs, une machine à comprimer l’humain au nom du rendement. Le débat dépasse l’entreprise : il interroge ce que l’on attend de la tech — l’invention, ou la simple optimisation de l’existant. Une chose est sûre : dans un continent qui rêve de champions, l’introduction en Bourse de Bending Spoons est un événement. La preuve, dérangeante mais réelle, qu’une réussite européenne massive peut naître non d’une idée neuve, mais d’un talent rare pour faire fructifier les idées des autres.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'bending-spoons-ressuscite-applis';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>Le mouvement gagne aussi la sphère publique, souvent la plus lente à changer. Des administrations et des collectivités, en Allemagne comme en France, migrent une partie de leurs outils vers des logiciels libres ou européens, par souci de coût, d’indépendance et de contrôle. Chaque bascule d’un service public envoie un signal : l’alternative n’est plus un pari de militant, mais un choix de gestionnaire.</p><p>Reste l’atout maître du continent : le règlement sur les données, souvent perçu comme un carcan, se révèle un avantage compétitif. À l’heure où la vie privée devient un argument de vente, être « conçu en Europe » signifie de plus en plus « conçu pour respecter l’utilisateur ». L’inertie des habitudes demeure le principal frein — on ne quitte pas un outil qu’on maîtrise sans raison forte. Mais chaque incident de confidentialité, chaque revirement d’un géant, rappelle pourquoi il est sage de ne pas mettre tous ses œufs dans le même panier américain.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'europe-outils-numeriques';

update public.radar_articles set body = replace(body,
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">',
'<p>Une image résume la bascule : Google est devenu la nouvelle devanture. Avant même de voir votre enseigne, le client a vu votre fiche, vos photos, vos avis, et s’est fait une opinion. Et il fait tout cela depuis son téléphone, dans la rue, en quelques secondes — ce qui impose une exigence nouvelle : être lisible, rapide et convaincant sur un petit écran, faute de quoi l’attention file ailleurs.</p><p>Dans cette vitrine numérique, quelques signaux font toute la confiance : des photos réelles et récentes, des avis nombreux et bien traités, un site qui se charge vite et dit clairement qui l’on est et comment le joindre. Rien de tape-à-l’œil : de la clarté et de la preuve. C’est peu, et c’est décisif — car dans le commerce de proximité, la première rencontre n’a plus lieu sur le pas de la porte, mais sur un écran. Autant qu’elle donne envie d’entrer.</p>' ||
'<p style="font-size:13px;color:#5c5852;margin-top:28px;border-top:1px solid #e3e0d8;padding-top:12px">')
where slug = 'presence-en-ligne-actif';
