// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});


/**
 * ─── Retenir une arrivée par lien d'invitation ────────────────────────
 *
 * Le lien de première connexion dépose le jeton dans l'adresse. Mais le
 * routeur redirige aussitôt un client vers son espace, et l'adresse — donc le
 * jeton — est perdue en route : l'écran « choisissez votre mot de passe » ne
 * s'affichait jamais, et le client se retrouvait connecté sans pouvoir
 * revenir un jour.
 *
 * On note donc le passage dès le chargement du module, avant toute
 * navigation. L'espace client lira ce drapeau et le consommera.
 */
export const MARQUE_MDP = "arsene.mdp-a-definir";

if (typeof window !== "undefined") {
  if (/type=(recovery|invite)/.test(window.location.hash)) {
    try { sessionStorage.setItem(MARQUE_MDP, "1"); } catch { /* mode privé */ }
  }
  supabase.auth.onAuthStateChange((e) => {
    if (e === "PASSWORD_RECOVERY") {
      try { sessionStorage.setItem(MARQUE_MDP, "1"); } catch { /* mode privé */ }
    }
  });
}
